### ISSUE TITLE
refresh_token过期怎么办？

### ISSUE THREAD

**Issue by tans** [overtrue/youzan#1]
是不是需要定期更新refresh_token

**Comment by overtrue** [comment]
哪里来的 refresh_token 哇？

**Comment by tans** [comment]
工具型不是都要维护refresh_token吗。 有赞的refresh_token还会变的。 不是像微信第三方平台那样授权了就固定。

**Comment by overtrue** [comment]
这个 SDK 没有为工具型应用做准备，而且目前的情况是有赞关掉了个人收款渠道，在没有通知用户的情况下，所以我也不打算支持了。感谢关注。
